In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count)

2.10.0+cpu
False
<function device_count at 0x790a0dabbe20>


In [2]:
# scalar
scalr = torch.tensor(7)
scalr

tensor(7)

In [3]:
scalr.ndim

0

In [4]:
# Get tensor back as Python int
scalr.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6 ]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # One three by three bracket

torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those numbers to better represent the data.


In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4284, 0.1524, 0.4245, 0.1663],
        [0.7515, 0.7573, 0.8748, 0.8064],
        [0.3588, 0.5566, 0.6274, 0.3007]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# Create a tensoe of all zeros
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor-like

In [21]:
# Use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(start=0, end=1000, step=42)

tensor([  0,  42,  84, 126, 168, 210, 252, 294, 336, 378, 420, 462, 504, 546,
        588, 630, 672, 714, 756, 798, 840, 882, 924, 966])

In [23]:
# Creating tensors like
one_to_ten = torch.arange(1, 11,1)
one_to_ten
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # datatype
                               device=None, # CPU/GPU
                               requires_grad=False # Wheter or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not the right datatype - to get datatype from a tensor, use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4366, 0.8101, 0.6320, 0.4378],
        [0.0548, 0.4353, 0.6065, 0.9568],
        [0.6945, 0.0394, 0.5843, 0.5750]])

In [29]:
# Find out detalis about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4366, 0.8101, 0.6320, 0.4378],
        [0.0548, 0.4353, 0.6065, 0.9568],
        [0.6945, 0.0394, 0.5843, 0.5750]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [32]:
# Subtract 10
tensor -10

tensor([-9, -8, -7])

In [33]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


In [34]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.59 ms, sys: 71 µs, total: 1.66 ms
Wall time: 3.66 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 478 µs, sys: 0 ns, total: 478 µs
Wall time: 378 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [39]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [41]:
print(tensor_A.shape, tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [42]:
tensor_A.shape

torch.Size([3, 2])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.


In [43]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [44]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [46]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [47]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [48]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [49]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [50]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positinal min and max

In [51]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [52]:
x.argmin()

tensor(0)

In [53]:
x[0]

tensor(1)

In [54]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [55]:
x[9]

tensor(91)

from types import WrapperDescriptorType
## Reshaping, stcking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shaped
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted ( swapped) in a certain way


In [56]:
# Create tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
# Ad an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [58]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [59]:
# Changing z changes x (because a view of a tensor shares the same memory as the original impput)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [60]:
# Stack tensors on top each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [61]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [62]:
# torch.squeeze() - removes all single dimensions from target tensor
x_reshaped

tensor([[5., 2., 3.],
        [5., 5., 6.],
        [5., 8., 9.]])

In [63]:
x_reshaped.shape

torch.Size([3, 3])

In [64]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [5., 5., 6.],
        [5., 8., 9.]])

In [65]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [66]:
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape

torch.Size([3, 3])

In [67]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(x_squeezed)
print(x_squeezed.shape)
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape
      )

tensor([[5., 2., 3.],
        [5., 5., 6.],
        [5., 8., 9.]])
torch.Size([3, 3])
tensor([[[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]])
torch.Size([1, 3, 3])


In [68]:
# torch.premute - rearrenges the dimensions of a trget tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channel]

# Premute the original tensor to rearrenge the axis (or dim) order
x_premuted = x_original.permute(2, 0, 1) # shifts axis 0->, 1->2, 2->0

print(x_original.shape)
print(x_premuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [69]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
# Let's index onthe middle bracket (dim=1)
x[0, 1]

tensor([4, 5, 6])

In [72]:
# Let's index on the most inner bracket (last dimension)
x[0,2,2]

tensor(9)

In [73]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [74]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [75]:
# Get index of 0 of 0th 1st dimension and all values of 2nd dimension
x[0,0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

PyTorch has functionality to interact with it

* Data in NumPy, wawnt a PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [76]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
array.dtype

dtype('float64')

In [78]:
tensor.dtype

torch.float64

In [79]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
numpy_tensor.dtype


dtype('float32')

In [81]:
# Change the tensor, what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...



In [82]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A ==random_tensor_B)

tensor([[0.3360, 0.1938, 0.1138, 0.2101],
        [0.7599, 0.0601, 0.9283, 0.5450],
        [0.9712, 0.6464, 0.2731, 0.6552]])
tensor([[0.9366, 0.0685, 0.9524, 0.2656],
        [0.6677, 0.2329, 0.6421, 0.0055],
        [0.0847, 0.3704, 0.9312, 0.7472]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [83]:
# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C ==random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects ont the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

## Check for GPU access with PyTorch

In [2]:
!nvidia-smi

Mon Feb 23 17:44:51 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Counte numbers of devices
torch.cuda.device_count()

1